language: objective-c

branches:
  only:
    - alfa
    - beta
    - stable

addons:
  sonarcloud:
    organization: "ydeagames-github"

os: osx

rvm:
  - 2.2

jdk:
  - oraclejdk8

cache:
  directories:
    # Homebrew
    - $HOME/Library/Caches/Homebrew
    # Unity
    - ./Unity
    - $HOME/Library/Caches/com.unity3d.UnityEditor/GiCache

install:
  - brew install tree
  - sh ./Travis/install.sh
  - sh ./Travis/install_android.sh

script:
  - sonar-scanner
  - tree
  - sh ./Travis/build.sh
  - tree

after_success:
  - sh ./Travis/tag.sh

deploy:
  - provider: releases
    api_key: $GIT_TOKEN
    file: 
      - ./Build/windows.zip
      - ./Build/linux.tar.gz
      - ./Build/android.apk
      - ./Build/osx.dmg
    name: $TRAVIS_BRANCH $(date +'%Y.%m.%d %H:%M')
    skip_cleanup: true
    on:
      all_branches: true

  - provider: pages
    skip-cleanup: true
    github-token: $GIT_TOKEN
    local-dir: ./Build/webgl/
    keep-history: true
    on:
      branch: stable

notifications:
  email: true