language: objective-c

branches:
  only:
    - release
    - master
    - develop

os: osx

rvm:
  - 2.2

addons:
  # Analytics
  sonarcloud:
    organization: "$SONAR_OWNER"

env:
  global:
    # Android
    - ANDROID_SDK_ROOT=/usr/local/share/android-sdk
    - ANDROID_NDK_HOME=/usr/local/share/android-ndk

cache:
  - directories:
    # Homebrew
    - $HOME/Library/Caches/Homebrew
    # Unity
    - ./Unity
    - $HOME/Library/Caches/com.unity3d.UnityEditor/GiCache
  - timeout: 1000

jobs:
  include:
    # Install
    - stage: install
      name: Install
      install:
        # Debug
        - brew install tree
        # Android
        - sh ./Travis/install_android.sh
        # Unity
        - sh ./Travis/install.sh
      script: sonar-scanner
    # Build Unity Projects
    - stage: build
      name: Build Windows
      script: sh ./Travis/build.sh windows
    #- name: Build OSX
    #  script: sh ./Travis/build.sh osx
    #- name: Build Linux
    #  script: sh ./Travis/build.sh linux
    - name: Build WebGL
      script: sh ./Travis/build.sh webgl
    - name: Build Android
      script: sh ./Travis/build.sh android
    #- name: Build iOS
    #  script: sh ./Travis/build.sh ios
    # Check
    - stage: check
      name: Check
      script:
        # Debug
        - tree -L 3
      after_success:
        # Notification
        - bash ./Travis/send.sh success $WEBHOOK_URL
    - stage: deploy
      name: Deploy
      script:
        # Tag
        - sh ./Travis/tag.sh
        # DeployGate
        - sh ./Travis/deploygate.sh $DEPLOYGATE_USER $DEPLOYGATE_API_TOKEN
      deploy:
        # GitHub
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: 
            - ./Build/windows.zip
            - ./Build/linux.tar.gz
            - ./Build/android.apk
            - ./Build/osx.dmg
            - ./Build/ios.zip
          name: $TRAVIS_BRANCH $(date +'%Y.%m.%d %H:%M')
          skip_cleanup: true
          on:
            all_branches: true
        # Pages
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          local-dir: ./Build/webgl/
          keep-history: true
          on:
            branch: develop

# Notification
notifications:
  email: false
