language: objective-c

branches:
  only:
    - alfa
    - beta
    - stable

os: osx

rvm:
  - 2.2

addons:
  sonarcloud:
    organization: "ydeagames-github"

env:
  global:
    - ANDROID_SDK_ROOT=/usr/local/share/android-sdk
    - ANDROID_NDK_HOME=/usr/local/share/android-ndk

cache:
  directories:
    # Homebrew    
    - $HOME/Library/Caches/Homebrew
    # Android
    - $ANDROID_SDK_ROOT
    - $ANDROID_NDK_HOME
    # Unity
    - ./Unity
    - $HOME/Library/Caches/com.unity3d.UnityEditor/GiCache

install:
  - brew install tree
  # Unity
  - sh ./Travis/install.sh
  # Android
  - echo "Attempting to Install Android SDK and NDK"
  - brew tap homebrew/cask
  - brew tap homebrew/cask-versions 
  - brew cask uninstall java # uninstall java9 
  - brew cask install java8 # install java8 
  - mkdir -p ~/.android/
  - touch ~/.android/repositories.cfg
  - brew cask install android-sdk
  - brew cask install android-ndk
  - yes | sdkmanager --licenses > /dev/null
  - sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3" > /dev/null

script:
  - sonar-scanner
  - tree
  - sh ./Travis/build.sh
  - tree

after_success:
  - sh ./Travis/tag.sh

deploy:
  - provider: releases
    api_key: $GIT_TOKEN
    file: 
      - ./Build/windows.zip
      - ./Build/linux.tar.gz
      - ./Build/android.apk
      - ./Build/osx.dmg
    name: $TRAVIS_BRANCH $(date +'%Y.%m.%d %H:%M')
    skip_cleanup: true
    on:
      all_branches: true

  - provider: pages
    skip-cleanup: true
    github-token: $GIT_TOKEN
    local-dir: ./Build/webgl/
    keep-history: true
    on:
      branch: stable

notifications:
  email: true