language: objective-c

branches:
  only:
    - alfa
    - beta
    - stable

os: osx
osx_image: xcode10.2

rvm:
  - 2.2

addons:
  sonarcloud:
    organization: "ydeagames-github"

env:
  global:
    - ANDROID_SDK_ROOT=/usr/local/share/android-sdk
    - ANDROID_NDK_HOME=/usr/local/share/android-ndk

cache:
  - directories:
    # Homebrew    
    - $HOME/Library/Caches/Homebrew
    # Android
    - $ANDROID_SDK_ROOT
    - $ANDROID_NDK_HOME
    # Unity
    - ./Unity
    - $HOME/Library/Caches/com.unity3d.UnityEditor/GiCache
  - timeout: 1000

before_install:
  - sleep 2
  # travis encrypt-file
  - openssl aes-256-cbc -K $encrypted_97826f4a0cf3_key -iv $encrypted_97826f4a0cf3_iv -in ./Travis/Secrets/secrets.tar.enc -out ./Travis/Secrets/secrets.tar -d
  - tar xvf ./Travis/Secrets/secrets.tar -C ./Travis/Secrets
  # xcpretty and fomrmatter
  - gem install xcpretty-travis-formatter --no-document

install:
  - brew install tree
  - sh ./Travis/install.sh
#  - sh ./Travis/install_android.sh

before_script:
  # Create default keychain on VM
  # http://docs.travis-ci.com/user/common-build-problems/#Mac%3A-Code-Signing-Errors
  - security create-keychain -p travis ios-build.keychain
  - security default-keychain -s ios-build.keychain
  - security unlock-keychain -p travis ios-build.keychain
  - security set-keychain-settings -t 3600 -l ~/Library/Keychains/ios-build.keychain
  # Add certs to keychain
  - security import ./Travis/Secrets/travis.p12 -k ~/Library/Keychains/ios-build.keychain -P ${KEY_PASSWORD} -T /usr/bin/codesign
  - security set-key-partition-list -S "apple-tool:,apple:" -s -k travis ios-build.keychain
  # save profile
  - mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
  - uuid=`grep UUID -A1 -a adhoc.mobileprovision | grep -io "[-A-F0-9]\{36\}"`
  - cp ./Travis/Secrets/travis.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$uuid.mobileprovision

script:
  - sonar-scanner
  - tree -L 3
  - sh ./Travis/build.sh
  - tree -L 3
  # iOS
  - cp ./Travis/Secrets/exportOptions.plist ./Build/ios/exportOptions.plist
  - cd ./Build/ios
  #- xcodebuild -project ${APP_NAME}.xcodeproj -configuration Release DEVELOPEMENT_TEAM="HL58UCA273" archive -sdk iphoneos -scheme ${APP_NAME} -archivePath ./build/${APP_NAME}.xcarchive -allowProvisioningUpdates | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}
  #- xcodebuild -exportArchive -archivePath ./build/${APP_NAME}.xcarchive -exportPath ./build.ipa -exportOptionsPlist ./exportOptions.plist -allowProvisioningUpdates | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}
  - xcodebuild -project ${APP_NAME}.xcodeproj -scheme ${APP_NAME} -configuration Release clean archive -archivePath ./build/${APP_NAME}.xcarchive DEVELOPMENT_TEAM="HL58UCA273" -allowProvisioningUpdates | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}
  - xcodebuild -exportArchive -archivePath ./build/${APP_NAME}.xcarchive -exportOptionsPlist ./exportOptions.plist -exportPath ./build.ipa -allowProvisioningUpdates | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}
  - cd ../../

after_success:
  - sh ./Travis/tag.sh
  # Upload .ipa file to deploygate
  - curl -F "file=@./Build/ios/build.ipa" -F "token=${DEPLOYGATE_API_TOKEN}" https://deploygate.com/api/users/${DEPLOYGATE_USER}/apps

after_script:
  - security delete-keychain ios-build.keychain
  - rm -f "~/Library/MobileDevice/Provisioning Profiles/${PROFILE_NAME}.mobileprovision"

deploy:
  - provider: releases
    api_key: $GIT_TOKEN
    file: 
      # - ./Build/windows.zip
      # - ./Build/linux.tar.gz
      # - ./Build/android.apk
      # - ./Build/osx.dmg
      - ./Build/ios/build.ipa
    name: $TRAVIS_BRANCH $(date +'%Y.%m.%d %H:%M')
    skip_cleanup: true
    on:
      all_branches: true

#  - provider: pages
#    skip-cleanup: true
#    github-token: $GIT_TOKEN
#    local-dir: ./Build/webgl/
#    keep-history: true
#    on:
#      branch: stable

notifications:
  email: true