language: objective-c

branches:
  only:
    - alfa
    - beta
    - stable

addons:
  sonarcloud:
    organization: "ydeagames-github"

os: osx

rvm:
  - 2.2

jdk:
  - oraclejdk8

cache:
  directories:
    # Homebrew
    - $HOME/Library/Caches/Homebrew
    # Unity
    - ./Unity
    - $HOME/Library/Caches/com.unity3d.UnityEditor/GiCache

env:
  global:
    - ANDROID_SDK_ROOT=/usr/local/share/android-sdk
    - ANDROID_NDK_HOME=/usr/local/share/android-ndk

install:
  - echo "Attempting to Install NDK Bundle"
  - brew doctor
  - brew tap homebrew/cask
  - brew cask uninstall java # uninstall java9
  - brew tap homebrew/cask-versions
  - brew cask install java8 # install java8
  - touch ~/.android/repositories.cfg # without this file, error will occur on next step
  - brew cask install android-sdk
  - brew cask install android-ndk
  - sdkmanager "platform-tools"
  - sdkmanager "build-tools;23.0.1"
  - sh ./Travis/install.sh

script:
  - sonar-scanner
  - sh ./Travis/build.sh

after_success:
  - sh ./Travis/tag.sh

deploy:
  - provider: releases
    api_key: $GIT_TOKEN
    file: 
      - ./Build/windows.zip
      - ./Build/linux.tar.gz
      - ./Build/android.apk
      - ./Build/osx.dmg
    name: $TRAVIS_BRANCH $(date +'%Y.%m.%d %H:%M')
    skip_cleanup: true
    on:
      all_branches: true

  - provider: pages
    skip-cleanup: true
    github-token: $GIT_TOKEN
    local-dir: ./Build/webgl/
    keep-history: true
    on:
      branch: stable

notifications:
  email: true